version: 0.2

phases:
  install:
    commands:
      - npm install serverless -g
      - npm install
  build:
    commands:
      - sls deploy -v
  post_build:
    commands:
      - echo build complete